// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwowiclyjxsccovrkplt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3b3dpY2x5anhzY2NvdnJrcGx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2NDUzOTUsImV4cCI6MjA3NzIyMTM5NX0.wn9fMVS7UqgkLnJCzTjoMbZz-VIrSP0hD_ulgJYgXwk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});